source 'https://rubygems.org'
ruby '2.0.0'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'pry'
gem 'maruku'
gem 'haml'
gem 'typhoeus'
gem 'uglifier'
gem 'puma'
gem 'newrelic_rpm'
gem 'bacon', :group => :test